
--- to show 
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';


SELECT name AS TableName
FROM sys.tables;

SELECT *
FROM dbo.ACHL

SELECT DISTINCT AGENT
FROM dbo.ACHL

SELECT MAX (REVENUE) AS MAX_REVENUE
FROM dbo.ACHL

---OPTION A
-- select the max_revenue and description of the goods imported
SELECT *
FROM dbo.ACHL
WHERE REVENUE = (SELECT MAX(REVENUE) FROM ACHL);

---OPTION B
SELECT TOP 1*
FROM ACHL
ORDER BY REVENUE DESC;

--OPTION C 

SELECT *
FROM (
     SELECT *,ROW_NUMBER()OVER(ORDER BY REVENUE DESC) AS rn
	 FROM ACHL
	 )
AS ranked 
WHERE rn =1;

--
SELECT DISTINCT CONSIGNEE
FROM ACHL

---QUESTION 2 
--HOW MANY AGENTS IMPORT GOODS VIA ACHL  
SELECT COUNT (DISTINCT AGENT) AS Unique_agents
FROM ACHL 